"use client"

interface DailyDigestCardProps {
  digest: {
    summary_markdown: string
    mood_arc: string
    episode_count: number
    sundowning_detected: boolean
    trend_direction: string
    cdr_total: number
    action_items: string[]
  }
}

export function DailyDigestCard({ digest }: DailyDigestCardProps) {
  return (
    <div className="card p-5 flex flex-col gap-4">
      <div className="flex items-start justify-between">
        <div>
          <div className="micro">Today with Theodore</div>
          <h2 className="font-serif text-[18px] font-normal tracking-tight leading-tight m-0 mt-1">
            {digest.summary_markdown}
          </h2>
        </div>
        <span className="num text-[13px] text-[var(--ink-3)]">
          12 conversations · 4h 18m
        </span>
      </div>

      {/* Mood arc visualization */}
      <div>
        <div className="grid grid-cols-[80px_1fr] gap-3 items-center">
          <div className="font-mono text-[10px] text-[var(--ink-3)] uppercase tracking-wider">
            Mood arc
          </div>
          <div className="h-10 bg-[var(--paper-3)] border border-[var(--line-soft)] rounded-lg relative overflow-hidden">
            <svg viewBox="0 0 600 38" className="absolute inset-0 w-full h-full" preserveAspectRatio="none">
              <defs>
                <linearGradient id="mood-grad" x1="0" x2="1">
                  <stop offset="0%" stopColor="var(--amber)" />
                  <stop offset="35%" stopColor="var(--sage)" />
                  <stop offset="55%" stopColor="var(--rose)" />
                  <stop offset="75%" stopColor="var(--sage)" />
                  <stop offset="100%" stopColor="var(--sky)" />
                </linearGradient>
              </defs>
              <path 
                d="M0,22 C40,18 80,12 120,10 C170,8 200,12 240,16 C280,20 320,30 360,28 C400,26 440,16 480,14 C520,12 560,18 600,22"
                fill="none" 
                stroke="url(#mood-grad)" 
                strokeWidth="2.2" 
                strokeLinejoin="round" 
              />
              {/* Episode marker */}
              <circle cx="330" cy="29" r="3.5" fill="var(--rose)" />
              <line x1="330" y1="0" x2="330" y2="38" stroke="var(--rose)" strokeDasharray="2 3" opacity="0.5" />
            </svg>
          </div>
        </div>
        <div className="grid grid-cols-[80px_1fr] gap-3 items-center mt-1">
          <div></div>
          <div className="flex justify-between font-mono text-[9px] text-[var(--ink-3)] px-1">
            <span>6a</span><span>9a</span><span>12p</span><span>3p</span><span>6p</span><span>9p</span>
          </div>
        </div>
      </div>

      {/* Stats grid */}
      <div className="grid grid-cols-4 gap-2">
        <div className="digest-stat">
          <div className="digest-stat-label">Conversation</div>
          <div className="digest-stat-value">4h 18m</div>
          <div className="digest-stat-trend" style={{ color: 'var(--sage)' }}>↑ +42m vs avg</div>
        </div>
        <div className="digest-stat">
          <div className="digest-stat-label">Episodes</div>
          <div className="digest-stat-value">{digest.episode_count}</div>
          <div className="digest-stat-trend">
            {digest.sundowning_detected ? 'sundowning' : 'normal'}
          </div>
        </div>
        <div className="digest-stat">
          <div className="digest-stat-label">Trend</div>
          <div className="digest-stat-value">{digest.trend_direction}</div>
          <div className="digest-stat-trend">14-day window</div>
        </div>
        <div className="digest-stat">
          <div className="digest-stat-label">CDR total</div>
          <div className="digest-stat-value">{digest.cdr_total.toFixed(1)}</div>
          <div className="digest-stat-trend">mild stage</div>
        </div>
      </div>

      {/* Action items */}
      {digest.action_items.length > 0 && (
        <div>
          <div className="micro mb-2">Action items</div>
          <ul className="space-y-1">
            {digest.action_items.map((item, index) => (
              <li key={index} className="font-serif text-[13px] leading-relaxed text-[var(--ink-2)] flex items-start gap-2">
                <span className="text-[var(--ink-4)] mt-1">•</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Attribution */}
      <div className="pt-2 border-t border-[var(--line-soft)]">
        <div className="micro">Generated by Claude · 7:00 PM daily</div>
      </div>
    </div>
  )
}